openapi: 3.0.3
info:
  title: Money Tracking
  version: 0.0.1
servers:
  - url: http://http://localhost:7071/api/
tags:
  - name: setup
    description: Setup the database and it's tables
paths:
  /items:
    get:
      summary: Get all of the items in the database
      responses:
        '200':
          description: successful operation
    post:
      summary: Add a new item(s)
      requestBody:
        description: Item(s) to upload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/item'
          text/csv:
            schema:
              $ref: '#/components/schemas/item'
      responses:
        '200':
          description: successful operation
components:
  schemas:
    item:
      required:
        - location
        - amount
        - category_id
        - transaction_date
      type: object
      properties:
        location:
          type: string
          example: Chipotle
        amount:
          type: number
          example: 9.90
        category_id:
          type: integer
          example: 8
        transaction_date:
          type: string
          example: 1970-01-01
        