openapi: 3.0.3
info:
  title: Money Tracking
  version: 0.0.1
externalDocs:
  url: https://github.com/MicahWW/Money-Tracking-Functions
  description: The GitHub repo for the project this is documenting
servers:
  - url: http://localhost:7071/api/
tags:
  - name: setup
    description: Setup the database and it's tables
paths:
  /items:
    get:
      summary: Get all of the items in the database
      responses:
        '200':
          description: successful operation
    post:
      summary: Add a new item(s)
      requestBody:
        description: Item(s) to upload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          text/csv:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: successful operation
  /categories:
    get:
      summary: Get the listed categories
      responses:
        '200':
          description: successful operation
components:
  schemas:
    Item:
      required:
        - location
        - amount
        - category_id
        - transaction_date
      type: object
      properties:
        location:
          type: string
          example: Chipotle
        amount:
          type: number
          example: 9.90
        category:
          $ref: '#/components/schemas/Category'
        transaction_date:
          type: string
          example: 1970-01-01
    Location_Name:
      required:
        - provider_name
        - name
      type: object
      properties:
        provider_name:
          type: string
          example: "Chipotle Store 0101"
        name:
          type: string
          example: Chipotle
    Location_Category:
      required:
        - location
        - category_id
      type: object
      properties:
        location:
          type: string
          example: Chipotle
        category:
          $ref: '#/components/schemas/Category'
    Category:
      description: A category from the list provided by the endpoint /categories
      required:
        - id
        - label
      type: object
      properties:
        id:
          type: integer
          example: 1
        label:
          type: string
          example: Dining